name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/ci.yaml@7b3d415a47bf67024079ff9d9a0cbb96d7067276
    secrets: inherit

  example:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - name: build example
        run: go run github.com/bufbuild/buf/cmd/buf@v1.32.0 generate
        working-directory: example
